// src/utils/content-types.js

export function getContentType(ext) {
    const types = {
      jpg: 'image/jpeg',
      jpeg: 'image/jpeg', 
      png: 'image/png',
      gif: 'image/gif',
      webp: 'image/webp',
      svg: 'image/svg+xml',
      icon: 'image/x-icon',
      mp4: 'video/mp4',
      webm: 'video/webm',
      mp3: 'audio/mpeg',
      wav: 'audio/wav',
      ogg: 'audio/ogg',
      flac: 'audio/flac',
      aac: 'audio/aac',
      wma: 'audio/x-ms-wma',
      m4a: 'audio/mp4',
      m4v: 'video/mp4',
      mov: 'video/quicktime',
      pdf: 'application/pdf',
      txt: 'text/plain',
      md: 'text/markdown',
      zip: 'application/zip',
      rar: 'application/x-rar-compressed',
      json: 'application/json',
      xml: 'application/xml',
      ini: 'text/plain',
      js: 'application/javascript',
      yml: 'application/yaml',
      yaml: 'application/yaml',
      py: 'text/x-python',
      sh: 'application/x-sh',
      css: 'text/css',
      html: 'text/html',
      htm: 'text/html',
      php: 'text/php',
      sql: 'text/sql',
      csv: 'text/csv',
      xls: 'application/vnd.ms-excel',
      xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      doc: 'application/msword',
      docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      ppt: 'application/vnd.ms-powerpoint',
      pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    };
    return types[ext] || 'application/octet-stream';
}